In [ ]:
import os
import sys

import pandas as pd
import numpy as np

In [ ]:
def set_colab():
    # clone git repo to environment
    ! git clone "https://github.com/yogendra-singh-lab/U.S.-Hospital-Customer-Satisfaction-2016-2020-.git"

    # if the csv file already exist exit the function
    if os.path.isfile("/content/U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2016.csv"):
        return

    # collecting the kaggle key from user
    key = input("input the contents of ur kaggle.json file: ")

    # processes to instantiate the kaggle api and download the dataset
    ! pip install kaggle
    ! mkdir -p ~/.kaggle
    ! > ~/.kaggle/kaggle.json
    ! echo '$key' >> ~/.kaggle/kaggle.json
    ! chmod 600 ~/.kaggle/kaggle.json
    ! kaggle datasets download --force abrambeyer/us-hospital-customer-satisfaction-20162020 -p \
    "U.S.-Hospital-Customer-Satisfaction-2016-2020-/data"

    # unzip the downloaded file
    ! unzip "U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/us-hospital-customer-satisfaction-20162020.zip" -d \
    "U.S.-Hospital-Customer-Satisfaction-2016-2020-/data"

Cloning into 'U.S.-Hospital-Customer-Satisfaction-2016-2020-'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 41 (delta 11), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (41/41), done.
input the contents of ur kaggle.json file: {"username":"jimohrildwan","key":"9c6782ef2eb28e2a5bf4f803d173ea5c"}
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (5.0.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.3)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Downloading us-hospital-customer-satisfaction-20162020.zip to U.S.-Hospital-Customer-Satisfaction-2016-2020-/data
 80% 33.0M/41.0M [00:00<00:00, 21.6MB/s]
100% 41.0M/41.0M [00:01<00:00, 40.3MB/s]
Archive:  U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/us-hospital-customer-satisfaction-20162020.zip
  inflating: U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2016.csv
  inflating: U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2017.csv
  inflating: U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2018.csv
  inflating: U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2019.csv
  inflating: U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/cms_hospital_patient_satisfaction_2020.csv

In [ ]:
def set_path():
    print("if path to data not correct, input path manually\n\n")
    if "data" in os.listdir() or "Statistical testing and visualization" in os.listdir():
        # running from parent directory
        path = os.path.abspath(os.getcwd() + "\\data").replace("\\", "/") + "/"
        print(path)
        return path
        
    elif "colab" in str(get_ipython()):
        # running on colab
        set_colab()
        path = "U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/"
        print("\n\n", path)
        return path
    else:
        # mostlikely running in a sub directory of parent directory
        path = os.path.abspath(os.getcwd() + "\\..\\data").replace("\\", "/") + "/"
        print(path)
        return path
    print("if path to data not correct, input path manually")
path = set_path()

if path to data not correct, input path manually


fatal: destination path 'U.S.-Hospital-Customer-Satisfaction-2016-2020-' already exists and is not an empty directory.


 U.S.-Hospital-Customer-Satisfaction-2016-2020-/data/

In [ ]:
data2016 = pd.read_csv(path + "cms_hospital_patient_satisfaction_2016.csv", dtype= {0:"object"})
data2017 = pd.read_csv(path + "cms_hospital_patient_satisfaction_2017.csv", dtype= {0:"object"})
data2018 = pd.read_csv(path + "cms_hospital_patient_satisfaction_2018.csv", dtype= {0:"object"})
data2019 = pd.read_csv(path + "cms_hospital_patient_satisfaction_2019.csv", dtype= {0:"object"})
data2020 = pd.read_csv(path + "cms_hospital_patient_satisfaction_2020.csv", dtype= {0:"object"})

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (14,17,19,26) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
# joining all the dataset into one
data = pd.concat([data2016, data2017, data2018, data2019, data2020]).reset_index(drop=True)

In [ ]:
ind = data.hcahps_measure_id[data.hcahps_measure_id == "H_STAR_RATING"].keys()

In [ ]:
temp = data.loc[ind]

In [ ]:
(temp[["patient_survey_star_rating", "hospital_overall_rating"]]
 [(temp.patient_survey_star_rating == "Not Available") | (temp.hospital_overall_rating == "Not Available")]
 )

        patient_survey_star_rating hospital_overall_rating
220                  Not Available                       3
440                  Not Available           Not Available
825                  Not Available                       4
1540                 Not Available                       3
1760                 Not Available           Not Available
...                            ...                     ...
1653310              Not Available           Not Available
1653403              Not Available           Not Available
1653496              Not Available           Not Available
1653589              Not Available           Not Available
1653682              Not Available           Not Available

[7648 rows x 2 columns]

In [ ]:
(data.hcahps_answer_percent == "Not Available").sum() / len(data) * 100

11.227544819654069

In [ ]:
# data.to_csv(path + "bigdata.csv", index=False)

In [ ]:
# data = pd.read_csv(path + "bigdata.csv", dtype= {0:"object"})

In [ ]:
data

        Facility ID  ... Efficient use of medical imaging national comparison footnote
0            010001  ...                                                NaN
1            010001  ...                                                NaN
2            010001  ...                                                NaN
3            010001  ...                                                NaN
4            010001  ...                                                NaN
...             ...  ...                                                ...
1653678      670130  ...                                               19.0
1653679      670130  ...                                               19.0
1653680      670130  ...                                               19.0
1653681      670130  ...                                               19.0
1653682      670130  ...                                               19.0

[1653683 rows x 43 columns]

### Renaming columns for better parsing

In [ ]:
data.columns = [i.strip().lower().replace(" ", "_") for i in data.columns]

### Dealing with unuseful columns

In [ ]:
# print(list(data.columns))
old_col_names = data.columns

In [ ]:
unuseful_col_names = [i for i in old_col_names if "footnote" in i]
unuseful_col_names += ['address', 'zip_code', 'county_name', 'phone_number', 'hcahps_question', 'start_date', 'end_date']

In [ ]:
data.drop(columns=unuseful_col_names, inplace=True)

In [ ]:
data.head().style

### since `hcahps_linear_mean_value` and `patient_survey_star_rating` are representations of the boxed responses the two columns will be kept for this analysis

`Not Applicable` entries in these two columns will be represented with `np.nan` and `Not Available` with `0`,

then only rows with values greater than or equal to `0` values in both columns will be kept. This would take out all __boxed answer entries__,

a column called master_metric will be made. This column contains entries from both columns. Remember that any row entry that has a valid `patient_survey_star_rating` entry will have a `Not Applicable` entry (now `np.nan`) in `hcahps_linear_mean_value` and vice-versa. So both columns can be summed rowwise and no data will be lost

In [ ]:
data[["patient_survey_star_rating", "hcahps_linear_mean_value"]] = \
    (data[["patient_survey_star_rating", "hcahps_linear_mean_value"]]
        .applymap(lambda x: np.nan if x == "Not Applicable" else (0 if x == "Not Available" else x))
        ).astype("float") # convert the whole column entries to float

In [ ]:
# indices of entries greater than 0 and np nan in the two columns are kept

valid_row_indices = sorted((data[data["patient_survey_star_rating"] >= 0]).index.tolist() # indices of entries greater than 0 in data["patient_survey_star_rating"]
                            + (data[data["hcahps_linear_mean_value"] >= 0]).index.tolist()
                            )

In [ ]:
# slicing out all these valid_row_entries only
data = data.loc[valid_row_indices]

In [ ]:
# summing both columns up rowwise
data["master_metric"] = data[["patient_survey_star_rating", "hcahps_linear_mean_value"]].sum(1)

### Transformation stage
The data is reindexed to a MultiIndex of the `year` and `facility_id` column. This will give a better representation of the data by year and will be useful for the next steps

A new dataframe `finaldata` is created to make sure each hospital (`facility_id`) in a particular `year` is represented only once. This time the MultiIndex is swapped to  be `facility_id` and `year` to better represent the data to show the years a hospital occured in the the dataset.

All the unique star rating and linear score entries in `hcahps_measure_id` are represented as columns,

A list of tuples is created from the former df `data` where each tuple is for each row entry containing its `index`, its `hcahps_measure_id` value and its metric in `master_metric`. This list is used to loop through the data and insert the `master_metric` in it's right position 

```python
finaldata[index, hcahps_measure_id_value] = master_metric_value
```

In [ ]:
# a MultiIndex using the year and facility_id column for the data is created
data.set_index(["year", "facility_id"], inplace=True)

In [ ]:
data

                                     facility_name  ... master_metric
year facility_id                                    ...
2016 010001       SOUTHEAST ALABAMA MEDICAL CENTER  ...           3.0
     010001       SOUTHEAST ALABAMA MEDICAL CENTER  ...          84.0
     010001       SOUTHEAST ALABAMA MEDICAL CENTER  ...           2.0
     010001       SOUTHEAST ALABAMA MEDICAL CENTER  ...          90.0
     010001       SOUTHEAST ALABAMA MEDICAL CENTER  ...           3.0
...                                            ...  ...           ...
2020 670130                    SOUTHCROSS HOSPITAL  ...           0.0
     670130                    SOUTHCROSS HOSPITAL  ...           0.0
     670130                    SOUTHCROSS HOSPITAL  ...           0.0
     670130                    SOUTHCROSS HOSPITAL  ...           0.0
     670130                    SOUTHCROSS HOSPITAL  ...           0.0

[521726 rows x 23 columns]

In [ ]:
# data.drop_duplicates(subset = ["survey_response_rate_percent", "hospital_type", "hospital_ownership", "emergency_services", "meets_criteria_for_promoting_interoperability_of_ehrs"]).shape

In [ ]:
# removing all duplicate facility_id entries per year and storing as a dictionary
newdict = {}
for i in (i for i in set(data.index)):
    newdict[i[-1::-1]] = data.loc[i].iloc[0].values.tolist()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: PerformanceWarning: indexing past lexsort depth may impact performance.
  after removing the cwd from sys.path.

In [ ]:
# dictionary converted to dataframe
finaldata = pd.DataFrame.from_dict(newdict, orient="index", columns= data.columns)
finaldata = finaldata.loc[sorted(finaldata.index)]
finaldata.index = pd.MultiIndex.from_tuples(finaldata.index)
finaldata = finaldata.rename_axis(index = ("facility_id", "year"))


del newdict

In [ ]:
# all unique facility_id entries is represented as columns
finaldata[finaldata["hcahps_measure_id"].unique()] = np.nan

In [ ]:
finaldata.head(20)

                                     facility_name  ... H_COMP_1_LINEAR_SCORE
facility_id year                                    ...
010001      2016  SOUTHEAST ALABAMA MEDICAL CENTER  ...                   NaN
            2017  SOUTHEAST ALABAMA MEDICAL CENTER  ...                   NaN
            2018  SOUTHEAST ALABAMA MEDICAL CENTER  ...                   NaN
            2019  SOUTHEAST ALABAMA MEDICAL CENTER  ...                   NaN
            2020  SOUTHEAST ALABAMA MEDICAL CENTER  ...                   NaN
010005      2016     MARSHALL MEDICAL CENTER SOUTH  ...                   NaN
            2017     MARSHALL MEDICAL CENTER SOUTH  ...                   NaN
            2018     MARSHALL MEDICAL CENTER SOUTH  ...                   NaN
            2019     MARSHALL MEDICAL CENTER SOUTH  ...                   NaN
            2020          MARSHALL MEDICAL CENTERS  ...                   NaN
010006      2016    ELIZA COFFEE MEMORIAL HOSPITAL  ...                   NaN
            2017    ELIZA COFFEE MEMORIAL HOSPITAL  ...                   NaN
            2018    ELIZA COFFEE MEMORIAL HOSPITAL  ...                   NaN
            2019      NORTH ALABAMA MEDICAL CENTER  ...                   NaN
            2020      NORTH ALABAMA MEDICAL CENTER  ...                   NaN
010007      2016          MIZELL MEMORIAL HOSPITAL  ...                   NaN
            2017          MIZELL MEMORIAL HOSPITAL  ...                   NaN
            2018          MIZELL MEMORIAL HOSPITAL  ...                   NaN
            2019          MIZELL MEMORIAL HOSPITAL  ...                   NaN
            2020          MIZELL MEMORIAL HOSPITAL  ...                   NaN

[20 rows x 25 columns]

In [ ]:
# storing each master_metric entry its index and hcahps_measure_id entry
master_metric_rep = zip(((j,i) for (i,j) in data.index.tolist()), data["hcahps_measure_id"].to_list(), data["master_metric"].to_list())

In [ ]:
# looping through 
for i,j,k in master_metric_rep:
    finaldata.loc[i,j] = k

In [ ]:
finaldata.head().style

In [ ]:
# removing all other columns that are now redundant after this transformation
unuseful_col_names = ["hcahps_measure_id", "hcahps_answer_description", "patient_survey_star_rating",
                      "hcahps_answer_percent", "hcahps_linear_mean_value", "master_metric"
                      ]
finaldata.drop(columns=unuseful_col_names, inplace=True)

In [ ]:
finaldata.columns = [i.strip().lower().replace(" ", "_") for i in finaldata.columns]

In [ ]:
map = dict(data[["hcahps_measure_id", "hcahps_answer_description"]].drop_duplicates().apply(lambda x: x.str.lower().str.strip().str.replace(" ", "_")).values.tolist())
finaldata = finaldata.rename(columns = map)
finaldata = finaldata.apply(lambda x: x.replace(0, np.nan))

In [ ]:
# final shape of data
finaldata.shape

(23928, 40)

### the large amount null values in `h_comp_4_linear_score` and `h_comp_4_star_rating` resulted from the fact that the question `pain management` wasn't represented in 2018 data upwards

In [ ]:
(finaldata.isna()).sum() / len(finaldata) * 100

h_star_rating                 0.000000
h_comp_1_linear_score         0.000000
h_clean_linear_score          0.000000
h_clean_star_rating           0.000000
h_comp_1_star_rating          0.000000
h_comp_2_linear_score         0.000000
h_comp_2_star_rating          0.000000
h_comp_3_linear_score         0.000000
h_comp_3_star_rating          0.000000
h_comp_4_linear_score        59.800234
h_comp_4_star_rating         59.800234
h_comp_5_linear_score         0.000000
h_comp_5_star_rating          0.000000
h_comp_6_linear_score         0.000000
h_comp_6_star_rating          0.000000
h_comp_7_linear_score         0.000000
h_comp_7_star_rating          0.000000
h_hsp_rating_linear_score     0.000000
h_hsp_rating_star_rating      0.000000
h_quiet_linear_score          0.000000
h_quiet_star_rating           0.000000
h_recmnd_linear_score         0.000000
h_recmnd_star_rating          0.000000
dtype: float64

In [ ]:
for i,j in zip([data2016, data2017, data2018, data2019, data2020], range(2016, 2021)):
    print(j, "h_comp_4_linear_score".upper() in i["HCAHPS Measure ID"].values)

2016 True
2017 True
2018 False
2019 False
2020 False

In [ ]:
finaldata.to_csv(path + "finaldata.csv")